server:
  port: 8083

spring:
  profiles:
    active: dev

ice:
  app: 1
  storage:
    path: ./ice-data
  scan: com.ice.test
  poll-interval: 5
  heartbeat-interval: 10
  pool:
    parallelism: -1

test:
  value: 123
environment: dev
