server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  app: 1
#  server: zookeeper:localhost:2181,localhost:2182,localhost:2183
  server: localhost:18121
  scan: com.ice.test
  pool:
    parallelism: -1
test:
  value: 123
environment: dev