server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  init-timeout: 10000
  app: 1
  rabbit:
    port: 5672
    host: localhost
    username: guest
    password: guest
test:
  value: 123
environment: dev



