server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  app: 1
  rmi:
    port: 8210
    server: 127.0.0.1:8212
    communicate-port: 18210
  pool:
    core-size: 4
    max-size: 4
    keep-alive-seconds: 60
    queue-capacity: 60000
test:
  value: 123
environment: dev



